### ISSUE TITLE
强烈建议改回本地加载或提供一个完美本地打包解决方案

### ISSUE THREAD

**Issue by attsion** [NetDimension/NanUI#1]
原因有二:
1、方便本地打包，受限于网速原因，特别是内网问题。
2、无法解决多个程序不同cef版本问题，特别是前期变动频繁。

**Comment by XuanchenLin** [comment]
1、打包时可将cef的自解压文件一同打包，解包前先运行cef自解压文件。
2、为了在一段时间内兼容WinXP，cef版本不会更新。
