### ISSUE TITLE
StackOverflowException异常[BUG]

### ISSUE THREAD

**Issue by xiaohui1** [NetDimension/NanUI#100]
**BUG描述 / Describe the bug**
在移动图片后再次调整窗体大小时出现System.StackOverflowException异常

**系统环境 / Desktop :**
 - OS: [e.g. Windowx 10]
 - Version [e.g. 1909]

在HostWindowType.Borderless;模式下

我在网页里写入以下代码此时body标签添加了-webkit-app-region: drag; img 标签为-webkit-app-region: no-drag; 

在拖动图片移动后，拖动窗体边框调整窗体大小时出现System.StackOverflowException异常

![image](https://user-images.githubusercontent.com/23479608/79055095-c5877800-7c7c-11ea-
8479-7081679a2aa5.png)

![image](https://user-images.githubusercontent.com/23479608/79055113-ebad1800-7c7c-11ea-9e30-ee1d6540f986.png)

**异常信息 / Thrown Excpetion:**

**Comment by XuanchenLin** [comment]
我测试后反馈
