### ISSUE TITLE
[BUG]DragRegion错误

### ISSUE THREAD

**Issue by KurtCheng** [NetDimension/NanUI#108]
**BUG描述 / Describe the bug**

**BUG如何产生的 / To Reproduce:**

**截图 / Screenshots**

**系统环境 / Desktop :**
 - OS: [e.g. Windowx 10]
 - Version [e.g. 1809]

**异常信息 / Thrown Excpetion:**
DragRegion一直是取并集，当同一个dragregion大小发生变化时，会产生bug

**Comment by XuanchenLin** [comment]
已知晓，bug还原后处理。
