### ISSUE TITLE
这支持跨平台吗?

### ISSUE THREAD

**Issue by xLabel** [NetDimension/NanUI#11]
诸如：Ubuntu、OSX 等

**Comment by XuanchenLin** [comment]
不支持，这个目前用了大量的Windows API来实现无边框的窗体，这些API是Windows独有的，所以不能跨平台。再加上本人能力有限，对Linux和OSX开发一窍不通，所以也暂时没有支持跨平台的计划。如果需要跨平台可以考虑使用electron
