### ISSUE TITLE
[问题]如何指定生成的Fx文件夹路径？

### ISSUE THREAD

**Issue by ySirius** [NetDimension/NanUI#110]
**NanUI/Formium版本**
**NanUI/Formium Version**
0.6.3239.2

**操作系统 / Windows Version**
win10

**问题描述 / QUESTION**
如何指定生成的Fx文件夹路径？
或者不下载 指定使用本地的fx路径

**Comment by XuanchenLin** [comment]
直接指定Bootstrap的LibCefDir属性和LibCefResourceDir属性。

**Comment by ySirius** [comment]
![image](https://user-images.githubusercontent.com/24601858/88353240-48958f80-cd8f-11ea-9136-91cde4f55d3f.png)
属性不能set
