### ISSUE TITLE
[BUG] LoadHandler.OnLoadError 的问题

### ISSUE THREAD

**Issue by jrt324** [NetDimension/NanUI#113]
**BUG描述 / Describe the bug**
LoadHandler.OnLoadError 首次加载时，无论是设置StartUrl还是LoadUrl()都不会触发，直到下次加载正常的页面才会触发上次的错误

**NanUI 版本**
0.7.77.39944

**Comment by XuanchenLin** [comment]
这个问题已经确认，将在下个版本中解决，此版本由于cfx本身的问题无法解决。
