### ISSUE TITLE
NanUI中内置的nanui-command属性

### ISSUE THREAD

**Issue by jeason-kin** [NetDimension/NanUI#117]
**NanUI/Formium版本**
77.1.18.2

win10 20H2

最大化最小化功能需要鼠标双击才能实现，请问该属性就是这样的还是说我使用的方法不对？

**Comment by XuanchenLin** [comment]
如果实现nanui-command的节点的父节点带有可拖动标记（-webkit-app-region: drag）会造成无法点击或者需要多次点击才触发事件的问，解决方法是为带有nanui-command的节点设置不可拖动标记（-webkit-app-region: no-drag）。
例如一下示例：
```html
<div class="titlebar">
<span>Title Here</span>
<div class="commands">
<a nanui-command="close">X</a>
</div>
</div>
```
其中，titlebar被设置为可拖动（-webkit-app-region: drag），那么就必须将commands或者a标签设置为不可拖动（-webkit-app-region: no-drag），这样来避免无法点击或者需要多次点击才相应操作的问题。
