### ISSUE TITLE
[BUG]GetSource&ViewSource获取的代码不全

### ISSUE THREAD

**Issue by mixiaodiao** [NetDimension/NanUI#118]
**BUG描述 / Describe the bug**
在LoadHandler_OnLoadEnd中调用e.Frame.ViewSource或者e.Frame.GetSource获取的代码和在浏览器右击查看的源代码内容不一致
**BUG如何产生的 / To Reproduce:**
如果页面有通过按钮或其他方式切换显示的内容部分通过程序获取不到

**截图 / Screenshots**

**系统环境 / Desktop :**
 - OS: [e.g. Windowx 10]
 - Version [e.g. 1809]
.net core3.1+nanui0.7
**异常信息 / Thrown Excpetion:**

**Comment by XuanchenLin** [comment]
此处获取的源码仅限于通过http加载的源码，而非实际呈现的dom代码。例如使用react打包的代码，仅能获取index.html原本的内容，而无法获取到实际渲染之后的代码。如果需要实际代码，可以考虑使用CefDomVistitor的相关逻辑来实现。
[https://magpcss.org/ceforum/apidocs/projects/(default)/CefDOMVisitor.html](https://magpcss.org/ceforum/apidocs/projects/(default)/CefDOMVisitor.html)

**Comment by mixiaodiao** [comment]
非常感谢您的回复.我提到的问题也正是您所说的,通过viewsource看到的内容应该和通过浏览器-右击-查看代码的内容一样,但是我在使用nanui时遇到的情况是:
1,如果是个简单的页面<div>显示</div>	<div style="display:none">隐藏</div> 这个是会显示这一段的(和预期一致)
2,如果访问如https://weread.qq.com/i/wrwebsimplenjlogic/reader?bc=5b932070717ffc055b9d02e  (微信读书移动版任意内容)时,通过viewsource/getsource获取的内容只是当前呈现出来的内容部分(浏览器-右击-看源码是完整内容)
*访问此页面需要user-agent: Mozilla/5.0 (X11; U; Linux armv7l like Android; en-us) AppleWebKit/531.2+ (KHTML, like Gecko) Version/5.0 Safari/533.2+ Kindle/3.0+ Edg/86.0.4240.111
上面这一点也是我目前比较疑惑的
