### ISSUE TITLE
[问题]在使用0.8版本中使用的几个问题

### ISSUE THREAD

**Issue by alexljk** [NetDimension/NanUI#119]
**NanUI/Formium版本** 0.8.80.127
**NanUI/Formium Version**0.8.80.127

**操作系统 / Windows Version**
Win10

**问题描述 / QUESTION**
一、在0.8中如何使用0.7中的userCustom
public override HostWindowType WindowType => HostWindowType.Custom;

二、.net framework 4.8中 app.UseEmbeddedFileResource("http", "www.app.local", "build");如何使用？

**Comment by XuanchenLin** [comment]
1. 重载`CreateCustomHostWindow`方法，在此方法中设置自定义窗体。
2. 请阅读文档。
