### ISSUE TITLE
0.8版本中怎么使用之前的NetDimension.NanUI.Subprocess[问题]

### ISSUE THREAD

**Issue by alexljk** [NetDimension/NanUI#120]
**NanUI/Formium版本**0.8
**NanUI/Formium Version**0.8

**操作系统 / Windows Version**
win10

**问题描述 / QUESTION**
0.8版本中怎么使用之前的NetDimension.NanUI.Subprocess

**Comment by XuanchenLin** [comment]
创建 SubProcess 项目，RutimeBuilder 创建运行时以后，使用 WinFormium 的 RunAsSubprocess 方法创建子进程。

编译成功后，主项目初始化 CEF 环境的 ChromiumEnvironmentBuilder 使用 UseExternalSubprocess 方法指定 SubProcess 的路径，通常应该把子进程和主进程的应用程序放在一个目录下方便操作。

另外，与之前CFX内核的项目不同，如果特别设置了其他插件，需要在子进程执行相同的代码以确保主进程和子进程加载了相同的插件和环境。
