### ISSUE TITLE
[BUG]快速关闭打开几次偶发出现黑边

### ISSUE THREAD

**Issue by maxjove** [NetDimension/NanUI#121]
**BUG描述 / Describe the bug**
画面还有黑边
**BUG如何产生的 / To Reproduce:**
反复快速打开几次, 偶发几次黑边
**截图 / Screenshots**

**系统环境 / Desktop :**
 - OS: [e.g. Windowx 10]
 - Version [e.g. 1809]

**异常信息 / Thrown Excpetion:**
![0 8bug2](https://user-images.githubusercontent.com/3186008/99624059-6f778000-2a68-11eb-8fa7-3cdd6f7c408f.png)

**Comment by XuanchenLin** [comment]
此问题已做修改，但不知道有没有解决，请拉取新代码测试，看是否根治。
