### ISSUE TITLE
[REQUEST]增加.net 4.5支持

### ISSUE THREAD

**Issue by mrtylerzhou** [NetDimension/NanUI#122]
看到readme里最低支持版本是4.6，不知道能否支持.net 4.5.传统行业大部分电脑使用的操作系统是win7，默认带的是.net 4.5,使用非系统默认版本会对于大规模部署(客户分布很零散)带来不少麻烦

**Comment by XuanchenLin** [comment]
不会支持4.6.2以下的版本。
因为4.6.1是首个支持.NET STANDARD 2.0的Framework版本，而从4.6.2起步是为了匹配Win10的DPI缩放特性。
如果要匹配WIN7也个人的建议是打包.NET5.0框架，今天做了个测试，使用.NET 5.0的SelfContained打包并开启优化，32位单架构(包含32位CEF)可以控制到100m以内，Win7 SP1不需要安装框架和依赖就可运行。

**Comment by mrtylerzhou** [comment]
好的,谢谢.我试一下
