### ISSUE TITLE
需要志愿者参与测试

### ISSUE THREAD

**Issue by XuanchenLin** [NetDimension/NanUI#123]
今天在Windows 7系统（64位）进行NanUI兼容性测试时发现两个问题：
- 测试机器是一台XPS14Z笔记本，带有核显和独显，不使用独显启动示例程序时无边框窗体的影子渲染不正常，而使用独显运行时并没有这种现象。所以需要有具备核显和独显且系统是Win7的志愿者帮助测试我遇到的问题是否具有普遍性。
- 从示例程序启动亚克力窗体（尽管亚克力窗体并不是为Win7设计的）后会随机性的崩溃，所以也需要对此问题进行普遍性测试。

请测试，并反馈结果，谢谢。

**Comment by maxjove** [comment]
这边可以参与,目前用户电脑比较多样性,有笔记本,有电脑的

**Comment by XuanchenLin** [comment]
> 这边可以参与,目前用户电脑比较多样性,有笔记本,有电脑的

非常感谢！

由于我这两天没在家里所以没梯子，您提交问题的图片看不见，等我回去把图片上的问题详细分析下看看再做处理。
