### ISSUE TITLE
[问题]某些电脑上经常报外部组件发生异常的错误

### ISSUE THREAD

**Issue by maxjove** [NetDimension/NanUI#124]
**NanUI/Formium版本**
**NanUI/Formium Version**

**操作系统 / Windows 10 **

**问题描述 / QUESTION**
你好, 某些电脑上经常报外部组件发生异常的错误,知道这个原因吗
![image](https://user-images.githubusercontent.com/3186008/100410167-cef90f80-30a8-11eb-8afa-868935e8e9e6.png)

**Comment by XuanchenLin** [comment]
如果方便请提供错误堆栈，只有一个图无法判断问题。

另外上网搜了一下，找到篇文章说可能由360安全卫士引起。

https://my.oschina.net/8824/blog/3065678

**Comment by maxjove** [comment]
应该走到未捕获的异常里,我先再跟踪下, 后面会把系统日志贴出来
