### ISSUE TITLE
[BUG]对“audio/aac”格式不支持

### ISSUE THREAD

**Issue by SPARON** [NetDimension/NanUI#125]
**BUG描述 / Describe the bug**

**BUG如何产生的 / To Reproduce:**

**截图 / Screenshots**

**系统环境 / Desktop :**
 - OS: [e.g. Windowx 10]
 - Version [e.g. 1809]

**异常信息 / Thrown Excpetion:**

对“audio/aac”格式不支持。

**Comment by XuanchenLin** [comment]
Chromium是开源项目，闭源或者商业的多媒体格式都不受支持，如您说的aac音频，h264编码视屏等。目前默认支持ogg，mp3音频，ogv视频。

如果要支持闭源或商业格式媒体请自行编译CEF加入相关的编码器。
