### ISSUE TITLE
[问题]cef 偶发空白 , 在开发者工具里 发现 read disk cache failed 情况

### ISSUE THREAD

**Issue by maxjove** [NetDimension/NanUI#126]
**NanUI/Formium版本**
**NanUI/Formium Version**

**操作系统 / Windows 7**

**问题描述 / QUESTION**
cef 偶发空白 , 在开发者工具里 发现 read disk cache failed 情况

**Comment by XuanchenLin** [comment]
read disk cache failed 是由于启动了多个进程而又共用了相同的缓存目录。最常见的就是同一个应用程序启动多个实例。如果应用程序需要启动多个实例，需要在初始化环境时为每个实例设置不同的缓存目录，否则可能会造成后启动的实例无法使用Session，Cookie和LocalStorage的问题。

另外所谓的发白是什么意思？不加载内容么？如果下次白的时候看下任务管理器应用程序的CEF渲染进程是否已启动。

**Comment by maxjove** [comment]
应该已经加载, 操作着,突然因为什么原因, 卡死,变空白了.

**Comment by maxjove** [comment]
> read disk cache failed 是由于启动了多个进程而又共用了相同的缓存目录。最常见的就是同一个应用程序启动多个实例。如果应用程序需要启动多个实例，需要在初始化环境时为每个实例设置不同的缓存目录，否则可能会造成后启动的实例无法使用Session，Cookie和LocalStorage的问题。
> 
> 另外所谓的发白是什么意思？不加载内容么？如果下次白的时候看下任务管理器应用程序的CEF渲染进程是否已启动。


可能使用户开了多个 应用
另外咨询下
1.目前缓存目录自定义,和0.7一样吗?

**Comment by XuanchenLin** [comment]
一样的，在启动参数里面设置。

**Comment by maxjove** [comment]
发现了问题, 是内存泄漏了 尤其在32位情况下 ,内存持续增加 , 到1G左右 ,就会崩溃 
![image](https://user-images.githubusercontent.com/3186008/100887283-bf862600-34ef-11eb-92d6-28b8776642fc.png)

**Comment by maxjove** [comment]
![image](https://user-images.githubusercontent.com/3186008/100888637-50113600-34f1-11eb-9329-5c60c1ef4865.png)

**Comment by maxjove** [comment]
![image](https://user-images.githubusercontent.com/3186008/100888866-85b61f00-34f1-11eb-895d-dcb0d261df04.png)

**Comment by XuanchenLin** [comment]
能提供具体的代码吗？在执行什么操作的时候导致的内存泄露？

**Comment by maxjove** [comment]
运行的 复杂 VUE开发页面，　操作１０来次　页面后，内存就起来了

**Comment by XuanchenLin** [comment]
方便的话，把vue的发布结果发我一份，或者在线地址给一个，我需要测试并确定泄露的原因
