### ISSUE TITLE
内嵌iFrame的页面里调用不到GlobalObject注册的事件

### ISSUE THREAD

**Issue by maczhong** [NetDimension/NanUI#13]
内嵌iFrame的页面里调用不到GlobalObject.AddFunction注册的事件

因为是本地加载，IFrame的JS事件也不能用window.top.方法名()来调用

LoadHandler的LoadEnd事件中

e.frame.V8Context获取一直是null

找不到iFrame注册事件的地方

请求下帮助

谢谢作者

**Comment by XuanchenLin** [comment]
在InitializeChromium里禁用安全设置，这样不仅可以解决跨域ajax的问题，也能解决iframe不能调用父级窗口函数的问题。

`CommandLine.AppendSwitch("disable-web-security");`
