### ISSUE TITLE
nanui  关于 vue的demo

### ISSUE THREAD

**Issue by 312977** [NetDimension/NanUI#154]
能上个  自动启动 vue server的demo不，能在开发的时候模块热加载

**Comment by 312977** [comment]
我把wwwroot的文件替换成vue的就不行了。为什么

**Comment by XuanchenLin** [comment]
说说我自己开发的经验，我一般在开发软件时资源并不打包，而是直接访问前端server的地址。实践中我最常使用的是React，调试的时候访问http://localhost:5000，开发完以后再打包和集成。

另外根据您提的问题，我个人觉得没必要由软件来启动vue server，不建议发布软件的时候这样使用而应该使用npm run build命令通过webpack打包以后，再把打包之后的内容放wwwroot里。
