### ISSUE TITLE
[如果访问线上的Web,是有缓存和代理嘛？]

### ISSUE THREAD

**Issue by tongso** [NetDimension/NanUI#155]
**NanUI/Formium版本**
**NanUI/Formium Version**
0.8

**操作系统 / Windows Version**
windows10

**问题描述 / QUESTION**
如果访问线上的Web,是有缓存和代理嘛？我把代码更新到线上，好长一段时间才生效

**Comment by XuanchenLin** [comment]
处理缓存有多重方式，最佳方案是服务器端处理。当然，客户端处理也是可以的，启动的时候使用app.ClearCache方法即可在启动CEF前删除与之相关的本地缓存，但这也会同时清除cookies localstorage等等的缓存数据。

**Comment by tongso** [comment]
好的，谢谢
