### ISSUE TITLE
如何屏蔽某个http请求[问题]

### ISSUE THREAD

**Issue by maxjove** [NetDimension/NanUI#156]
**NanUI/Formium版本**
**NanUI/Formium Version**

**操作系统 / Windows Version**

**问题描述 / QUESTION**
目前在用nanui打开网页时, 由于客户现场网络环境复杂, 会被植入  http://1.1.1.3:89/cookie/flash.js
加载对象 ,会导致后面请求终止,页面白屏.
请问如何屏蔽某个http的连接?

**Comment by XuanchenLin** [comment]
BeforeBrowse事件可以提前判断URL，如果不需要某个URL可以进行处理。
