### ISSUE TITLE
路径中存在“#”符号将导致本地CEF环境检测失败

### ISSUE THREAD

**Issue by mghcool** [NetDimension/NanUI#157]
**NanUI/Formium版本**
0.8.80.176

**操作系统 / Windows Version**
win10

**问题描述 / QUESTION**
在使用.not core3.1创建程序时会出现：The CEF binary files are not found.

**Comment by XuanchenLin** [comment]
安装NetDimension.NanUI.Runtime包，如果已安装任然出现此问题，请判断软件目录是否存在“#”字符，目前发现路径中存在“#”符号会导致目录判断失败。在下次发布版本中将对此问题进行修复。

**Comment by XuanchenLin** [comment]
此问题0.9以修复
