### ISSUE TITLE
如何在WPF应用中启动NanUI

### ISSUE THREAD

**Issue by EveElseIf** [NetDimension/NanUI#158]
**NanUI/Formium版本**
**NanUI/Formium Version**
0.8.80.191

**操作系统 / Windows Version**
windows10 20h2

**问题描述 / QUESTION**
我习惯使用wpf编写业务逻辑，但是又需要用到一些js库和html页面。我尝试在wpf中启动NanUI，反应是弹出了若干个MainWindow类的窗口，然后NanUI窗口只停留在初始页面。

**Comment by XuanchenLin** [comment]
暂不支持wpf
