### ISSUE TITLE
使用http替代local、embedded等scheme

### ISSUE THREAD

**Issue by anheihb03dlj** [NetDimension/NanUI#16]
[1]: https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage#markdown-header-scheme-handler
cef3官方文档强烈建议不要自定义scheme，最好是使用内置scheme，比如: http、https，因为自定义的scheme有些时候可能会收不到POST的数据以及其它问题!!!

&nbsp;&nbsp;&nbsp;&nbsp;_Request Handling_ -> [Use the HTTP scheme instead of a custom scheme to avoid a range of potential issues.][1]

我创建了一个分支use_http_scheme，本地资源或程序集资源也可以使用http scheme。参见：PR #15

**Comment by XuanchenLin** [comment]
感谢提供解决方案，最近工作比较忙没能及时回复，稍后调试下你提供的代码。 @anheihb03dlj

**Comment by XuanchenLin** [comment]
已解决
