### ISSUE TITLE
[REQUEST] Automated build with GitHub Actions

### ISSUE THREAD

**Issue by aleks-ivanov** [NetDimension/NanUI#160]
**Automated build with GitHub Actions**

A simple GitHub Actions workflow to validate the build process each time a push commit is made or a PR is created.

Built with ❤ by [Pipeline Foundation](https://pipeline.foundation).

**Comment by XuanchenLin** [comment]
Thank you for your advice, but I don't understand how it works. I merged the PR, and how to do next?

**Comment by aleks-ivanov** [comment]
你好 @XuanchenLin 🙂

You are welcome, we are sure you will find the pipeline very beneficial long term.

So, the function of the pipeline currently is to validate the build process. This is especially beneficial on pull requests from contributors on GitHub, because you will be able to see before merging a PR, if the contribution breaks the application or not. 
On every PR, there is going to a be a GitHub check for the pipeline, which will tell immediately if there is a problem or not. 

![pr-checks-final](https://user-images.githubusercontent.com/74899441/112987143-0d8ffb00-916b-11eb-8cee-15b2120307b9.png)

Also you can create a badge for the pipeline and add it to the README, to show that the project is in a great shape! 
**Actions** tab -> NanUI CI/CD Pipeline -> on the right click on the **...** button and click on "Create status badge" -> select from the **Event** dropdown "push" -> click the "Copy status badge Markdown" and paste the value at the top of your README.md

![Screenshot_1](https://user-images.githubusercontent.com/74899441/112987454-6bbcde00-916b-11eb-8716-47df6951a4ce.png)

If you'd like, we would be happy contribute more DevOps features to NanUI, because as you may already have noticed we Pipeline Foundation are **a non-profit initiative** with the sole goal of assisting open source projects with their DevOps implementations. So, a couple of features to add to the current implementation would be automated test validation, automated NuGet publishing, dependency security and version scanning, code security and quality scanning etc.

If you find any of those ideas useful to you, please let us know and we would start working on them promptly 🙂
