### ISSUE TITLE
能否将WinFormium嵌入一个窗体中呢？

### ISSUE THREAD

**Issue by dante502** [NetDimension/NanUI#161]
比如这样的情况，上半部分为C#的原生控价，下半部分为WinFormium的Html控件，这样做可以吗？如果可以的话应该怎么弄呢？

**Comment by XuanchenLin** [comment]
NanUI在0.8之前的版本都提供以控件方式嵌入窗体，但考虑到后期主要以应用程序界面渲染这一主题为主，所以把控件从NanUI项目里剔除了。后面有空我会另外发起一个新项目来实现这个需求。

**Comment by dante502** [comment]
> NanUI在0.8之前的版本都提供以控件方式嵌入窗体，但考虑到后期主要以应用程序界面渲染这一主题为主，所以把控件从NanUI项目里剔除了。后面有空我会另外发起一个新项目来实现这个需求。

好的，感谢回复，主要现在遇到一些场景，比如对接一些摄像头厂商的SDK，播放器只能嵌入到原生控件中。

**Comment by yeyuxuan9875** [comment]
我也有这个需求，海康威视的摄像头，需要显示实时视频

**Comment by XuanchenLin** [comment]
使用webrtc可以实现使用video标签来播放摄像头视频流，之前有个哥们弄过，具体怎么实现的忘了。

**Comment by dante502** [comment]
> 使用webrtc可以实现使用video标签来播放摄像头视频流，之前有个哥们弄过，具体怎么实现的忘了。

这样有些大费周章了，我也实现过转rtmp流的，但是需要再搭建一个服务，过于繁琐。

**Comment by sudongg** [comment]
> NanUI在0.8之前的版本都提供以控件方式嵌入窗体，但考虑到后期主要以应用程序界面渲染这一主题为主，所以把控件从NanUI项目里剔除了。后面有空我会另外发起一个新项目来实现这个需求。

我也有这个需求，有时候并不需要整个窗口都使用网页，或者一个窗口同时使用两个WinFormium。
