### ISSUE TITLE
您好，请教您一个问题，地址Url加载失败的时候，应用无法正常退出

### ISSUE THREAD

**Issue by WangPengyun123** [NetDimension/NanUI#163]
应用如果加载了一个正常的网页，关闭窗口的时候应用可以正常退出！！！
但是当应用加载地址不存在或者加载失败的时候，关闭窗口，应用线程没有正常退出，不知道有没有什么更好的处理方法，或者是我这里的写法有问题
![image](https://user-images.githubusercontent.com/32721579/111717557-383ca280-8893-11eb-8b30-5ed3a1d8c214.png)

**Comment by XuanchenLin** [comment]
请不要使用Application.Exit方法来退出程序，CEF采用多进程架构，Application.Exit方法退出的时候很有可能会导致进程残留，具体为何残留我没有研究过，无法给出准确的回答。

使用Close(true)方法试试强制关闭能否达到要求。
