### ISSUE TITLE
[REQUEST]使用Costura.Fody打包单文件报"路径的形式不合法"

### ISSUE THREAD

**Issue by yanhan-dev** [NetDimension/NanUI#164]
非常感谢您设计了NanUI
当我安装NuGet中Costura.Fody准备进行单文件生成的时候报错
路径的形式不合法。
   在 System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   在 System.IO.Path.InternalGetDirectoryName(String path)
   在 System.IO.Path.GetDirectoryName(String path)
   在 NetDimension.NanUI.WinFormium.get_ApplicationRunningDirectory()
   在 NetDimension.NanUI.ChromiumEnvironmentBuilder.DetectLibCefFilesPath()
   在 NetDimension.NanUI.ChromiumEnvironmentBuilder.AutoDetectCefBinaryPath()
   在 NetDimension.NanUI.ChromiumEnvironmentBuilder.Build()
   在 NetDimension.NanUI.RuntimeBuilder..ctor(Action`1 buildChromiumEnvironment, Action`1 configureAppConfiguration)
   在 NetDimension.NanUI.WinFormium.CreateRuntimeBuilder(Action`1 buildChromiumEnvironment, Action`1 buildApplicationConfiguration)
   在 WindowsFormsApp2.Program.Main() 在 C:\Users\luanf\source\repos\WindowsFormsApp2\WindowsFormsApp2\Program.cs 中: 第 18 行

**Comment by XuanchenLin** [comment]
暂时不支持单文件打包，我没接触过Fody，刚搜索了下，它的原理和.net core单文件打包原理似乎一样，所以在启动前都会解压到一个临时目录里运行，而这个过程不会将cef的相关文件解压到正确的位置，因此无法找到cef的文件导致报错。

要解决这个问题有2个方法：
1、使用手动指定CEF运行时文件的位置（使用UseCustomCefBinaryPath方法或者在IfLibCefNotFound回调里指定）
2、将CEF的包文件放置到公共位置，这个位置在%PROGRAMDATA%\Net Dimension Studio\NanUI\<CEF版本号>\这个位置下面。也可以从百度网盘下载自解压包https://pan.baidu.com/s/11S6iXZBtLv1NdtmzMZyTsQ 提取码: v351
