### ISSUE TITLE
[问题]

### ISSUE THREAD

**Issue by Killif7** [NetDimension/NanUI#165]
包引用
```
<PackageReference Include="NetDimension.NanUI" Version="0.8.80.191" />
<PackageReference Include="NetDimension.NanUI.EmbeddedFileResource" Version="0.8.80.176" />
<PackageReference Include="NetDimension.NanUI.Runtime" Version="80.1.15" />
<PackageReference Include="NetDimension.NanUI.ZippedResource" Version="0.8.80.176" />
```

**操作系统 / Win10**

**问题描述 / QUESTION**
第一个问题：
设置public override HostWindowType WindowType =>  HostWindowType.System;调试能正常显示自定义网页
![image](https://user-images.githubusercontent.com/14232671/113475609-51f00380-94a9-11eb-822b-361eb7efb198.png)

设置public override HostWindowType WindowType =>  HostWindowType.Borderless;调试则无法渲染网页出来，显示如下
![image](https://user-images.githubusercontent.com/14232671/113475628-70ee9580-94a9-11eb-8bb2-bcce224ed2a3.png)

第二个问题：
把网页的样式和脚本文件打包进lib.zip并添加到项目资源
然后初始化
```
app =>
            {
                app.UseZippedResource("http", "zip.local",()=> new MemoryStream(Properties.Resources.lib));
                app.UseEmbeddedFileResource("http", "assembly.app.local", "wwwroot");
                // 指定启动窗体
                app.UseMainWindow(context => new LoginWindow());
            })
```
在网页中把引用的路径改为

```
<link rel="stylesheet" href="http://zip.local/lib/layui/css/layui.css" />
    <script src="http://zip.local/lib/layui/layui.js"></script>
    <script src="http://zip.local/lib/jquery-3.6.0.min.js"></script>
    <style>
        .bg {
            width: 430px;
            height: 330px;
            background-image: url(http://zip.local/lib/icons/u3583.png);
            background-size: cover;
        }

```
无法引用成功

**Comment by XuanchenLin** [comment]
第一个问题，检测你的网页是不是有没有完成的请求还在执行，看你的截图图标并没有出来，如果使用了外网资源网络阻塞会导致页面的LoadEnd不触发，如果LoadEnd不触发就会造成一直显示加载画面。

第二个问题，因为不好判断是为何引用失败，请贴出zip文件的结构，http://zip.local/后面的目录结构需要跟zip文件保持一直，另外zip不能加密。
