### ISSUE TITLE
新窗口 关闭 最小化 最大化 不起作用

### ISSUE THREAD

**Issue by hpsocket** [NetDimension/NanUI#17]
NanUI.Demo.Welcome     about窗口

**Comment by XuanchenLin** [comment]
这个问题还没有找到解决方法，使用Form.Show, Form.ShowDialog创建的子窗体，如果参数中传入了父窗体的实例，那么子窗体中的js都无法执行。

**Comment by XuanchenLin** [comment]
没有跟踪内容，关闭
