### ISSUE TITLE
[BUG]软件退出时，windows事件会产生错误

### ISSUE THREAD

**Issue by toplevmas** [NetDimension/NanUI#173]
**BUG描述 / Describe the bug**
软件退出时，windows事件会产生错误，看事件描述，最终定位到libcef，每次退出都有这个错误。
打开windows 事件查看器，可找到

**BUG如何产生的 / To Reproduce:**
退出应用时

**系统环境 / Desktop :**
 - OS: [Window 10]

**异常信息 / Thrown Excpetion:**
Application Error:

错误应用程序名称: WindowsFormsApp2.exe，版本: 1.0.0.0，时间戳: 0xee24bb6a
错误模块名称: libcef.dll，版本: 77.1.18.0，时间戳: 0x5d9d2608
异常代码: 0xc0000005
错误偏移量: 0x00000000038abee3
错误进程 ID: 0x81c

.NET Runtime:

应用程序: WindowsFormsApp2.exe
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: 异常代码为 c0000005，异常地址为 00007FFE0DF3BEE3
堆栈:

**Comment by XuanchenLin** [comment]
如果使用了WebSocket，请确保退出时每个进程上的WebSocket正确的释放。

**Comment by toplevmas** [comment]
定位到了，底层CfxRuntime.Shutdown() 引起的。和websocket无关，所有页面均有这个问题

**Comment by XuanchenLin** [comment]
@toplevmas 新版本的NanUI已将内核更换位CefGlue，老版本的由于ChromiumFX不再更新，因此有很多问题无法解决，所以建议切换到新版本以解决这些莫名其妙的问题。如果这个问题出现在Shutdown，多半猜测是CFX内部使用的进程间通信出现问题。
