### ISSUE TITLE
打开DEMO 显示红框 这个是BUG吗 [BUG]

### ISSUE THREAD

**Issue by kindeeking** [NetDimension/NanUI#175]
**BUG描述 / Describe the bug**
运行FormiumClient 出现下面的红框
**BUG如何产生的 / To Reproduce:**

**截图 / Screenshots**
![image](https://user-images.githubusercontent.com/86276635/123905388-d49f3680-d9a4-11eb-834c-ecfa8fd69abb.png)

**系统环境 / Desktop :**
 - OS: [e.g. Windowx 10]
 - Version [e.g. 1809]

**异常信息 / Thrown Excpetion:**

**Comment by XuanchenLin** [comment]
抱歉，昨天提交的时候提交错了，本来应该提交到私有仓库的，结果提交到这里了，稍后会修复这个问题。
