### ISSUE TITLE
如何隐藏About弹出?

### ISSUE THREAD

**Issue by BenLampson** [NetDimension/NanUI#176]
如何隐藏或者替换about内的描述内容?
![image](https://user-images.githubusercontent.com/15414750/124216401-cda13100-db28-11eb-85c8-3adbef482490.png)
![image](https://user-images.githubusercontent.com/15414750/124216412-d42fa880-db28-11eb-8e9b-3945d90bc36a.png)

**Comment by XuanchenLin** [comment]
自行编译NanUI源码，并修改WinFormium.cs属性DisableAboutMenu => false为DisableAboutMenu => true

但关闭关于对话框后，需按照MIT协议之规定，在软件适当的地方加入NanUI版权申明。
