### ISSUE TITLE
如何关闭调试窗口[问题]

### ISSUE THREAD

**Issue by maxjove** [NetDimension/NanUI#177]
**NanUI/Formium版本**
**NanUI/Formium Version**
NanUI 0.8

**操作系统 / Windows Version**

**问题描述 / QUESTION**
如何关闭如下 调试窗口
![image](https://user-images.githubusercontent.com/3186008/124342456-aca71180-dbf6-11eb-8d7c-38bc7bc1d3b7.png)

**Comment by XuanchenLin** [comment]
项目属性里编译类型改成Windows 应用程序，或者直接修改csproj文件，把输出类型从Exe改为WinExe
