### ISSUE TITLE
[BUG]点击窗口周围阴影区域时阴影会闪烁

### ISSUE THREAD

**Issue by sudongg** [NetDimension/NanUI#178]
**BUG描述 / Describe the bug**
点击窗口周围阴影区域时阴影会闪烁，任务栏也跟着闪烁

**BUG如何产生的 / To Reproduce:**
打开应用连续点击阴影区域就会发生

**系统环境 / Desktop :**
 - OS: [e.g. Windowx 10]
 - Version [e.g. 1809]

我在测试同样是 NetDimension 的项目 WinForm-ModernUI 时，点击阴影未发现闪烁的问题，但 WinForm-ModernUI 在窗口切换最大化状态到还原状态的时候会出现闪烁，闪烁的时候能看到窗口后面的内容。

**Comment by XuanchenLin** [comment]
WinForm-ModernUI 已经没有维护，核心技术已并入NanUI。如果项目中有用到无边框窗口技术可以参考NanUI项目的HostWindow部分代码。不过无边框窗口承载浏览器窗口可以，但是如果要置入其他WinForms控件在非标准DPI环境下渲染会出现问题，这个问题我个人无力解决，这也是我关闭WinForm-ModernUI项目的原因。

感谢关注。

**Comment by sudongg** [comment]
> WinForm-ModernUI 已经没有维护，核心技术已并入NanUI。如果项目中有用到无边框窗口技术可以参考NanUI项目的HostWindow部分代码。不过无边框窗口承载浏览器窗口可以，但是如果要置入其他WinForms控件在非标准DPI环境下渲染会出现问题，这个问题我个人无力解决，这也是我关闭WinForm-ModernUI项目的原因。
> 
> 感谢关注。

你好，可能是我没有表达清楚，点击阴影会闪烁这个问题出现在NanUI上而不是WinForm-ModernUI 。

**Comment by XuanchenLin** [comment]
能提供视频或者图片么？

**Comment by sudongg** [comment]
> 能提供视频或者图片么？

优酷链接： https://v.youku.com/v_show/id_XNTE4ODgyNDE0OA

**Comment by XuanchenLin** [comment]
@sudongg 这个闪烁在这个版本是正常的。四周的影子是四个窗体，当点击任意一个窗体改变大小的时候首先会让主窗体失去焦点，然后影子再通知主窗体获取焦点，因此就产生了闪烁的问题。

这个问题将在正在开发的新版本里解决，新版本重新优化了承载窗体的逻辑，决绝了焦点混乱的问题。

**Comment by sudongg** [comment]
> @sudongg 这个闪烁在这个版本是正常的。四周的影子是四个窗体，当点击任意一个窗体改变大小的时候首先会让主窗体失去焦点，然后影子再通知主窗体获取焦点，因此就产生了闪烁的问题。
> 
> 这个问题将在正在开发的新版本里解决，新版本重新优化了承载窗体的逻辑，决绝了焦点混乱的问题。

期待新版本，我希望新版本能将网页浏览器做成单独的控件或可以附加到继承某个接口的控件上，不再依赖于窗口。

**Comment by sudongg** [comment]
> @sudongg 但NanUI设计的初衷就是为了用Chromium核心来渲染软件界面，如果希望使用单纯的浏览器的话建议考虑采用CefSharp或者微软Chromium核心的Edge浏览器控件WebView2，这两个都能方便作为控件嵌入到任意Form或者Panel等等容器控件里。

NanUI用的是CefGlue，就支持多平台这点我更喜欢CefGlue，虽然目前没有多平台的需求。
但是，NanUI给CefGlue添加许多方便的功能，比如c#和js交互更加方便灵活，简单的设置便可访问本地网页或者加载本地zip资源，还有数据资源处理器等等。但想使用这些，你必须使用Formium，而Formium是都会带有一个窗口。感觉这中间缺少了一层，也就是没有窗口但是具有那些方便功能的网页浏览器。
但是我想要的正好是这个。
