### ISSUE TITLE
[问题]

### ISSUE THREAD

**Issue by jacobSpitzer** [NetDimension/NanUI#180]
**NanUI/Formium版本**
**NanUI/Formium Version**

**操作系统 / Windows Version**

**问题描述 / QUESTION**
How to use this library with HTML basic. WITHOUT React?

**Comment by XuanchenLin** [comment]
React is not necessary to build an application. You can choose any front-end technology you like to make the UI.

Then use EmbeddedFileResource or LocalFileResource libraries to organize your HTML files. You should look at the FormiumClient project in the source code to learn how to use these libraries.
