### ISSUE TITLE
您好，请问NanUI有计划或者有可能支持Linux吗

### ISSUE THREAD

**Issue by WangPengyun123** [NetDimension/NanUI#181]
**NanUI/Formium版本**
**NanUI/Formium Version**

**操作系统 / Windows Version**

**问题描述 / QUESTION**

**Comment by lujiaxing** [comment]
应该支持不来. NanUI 无论怎么说都是基于 WinForms 技术的. 微软官方也从来没有试图把 WinForms 技术向跨平台方向演进过. 毕竟 WinForms 本质上就是 GDI+ 的托管封装, 而这东西是不能跨平台的.

**Comment by XuanchenLin** [comment]
不支持，WinForm只支持Windows
