### ISSUE TITLE
[问题]

### ISSUE THREAD

**Issue by YueYunyun** [NetDimension/NanUI#182]
**NanUI/Formium版本**
**NanUI/Formium Version**
Chromium 80.0.3987.163
NanUI 0.8.80.120

**操作系统 / Windows Version**
Win10

**问题描述 / QUESTION**
HTML 中 a标签  traget="_blank" 以及 JS 的 window.open()   打开的新窗口可以指定窗口样式吗？ 我尝试了都是  HostWindowType.System 这个样式。
这样打开的窗口样式可以配置吗？如果可以在哪配置呢？

**Comment by XuanchenLin** [comment]
如果要定制弹出窗口需要自行在BeforePopup事件中拦截弹窗并用自定义的窗口替代默认窗体。
