### ISSUE TITLE
[BUG] JavaScriptValue.CreateFunction 对象如果存在空值会错出

### ISSUE THREAD

**Issue by zhouge870103** [NetDimension/NanUI#183]
C#
obj.SetValue("test", JavaScriptValue.CreateFunction(args=> {

                return JavaScriptValue.CreateNull();
}));
js
Formium.external.test({a:'',b:''})

![1631884484(1)](https://user-images.githubusercontent.com/13454176/133788535-f6344bc0-cf65-4c12-af00-1735243fdcd3.png)

**Comment by XuanchenLin** [comment]
0.9已重写JavaScript Bridge，该问题已修复
