### ISSUE TITLE
[在使用亚克力窗口的时候，界面异常卡顿以至于整个系统桌面都卡了]

### ISSUE THREAD

**Issue by superowner** [NetDimension/NanUI#184]
varsion 0.8.80.157 .Net Core 3.1

win11 x64 pro

在使用亚克力窗口的时候，界面异常卡顿以至于整个系统桌面都卡了（.Net472里得亚克力没有发现这个问题）
每次打开都会发生。

**Comment by XuanchenLin** [comment]
这个问题发生在很多笔记本电脑的windows系统上，因为使用了微软未公开的API，所以不敢判断问题的根源，后面版本可能会考虑移除这个样式。

**Comment by XuanchenLin** [comment]
正在开发的0.9版本已移除亚克力窗口样式，亲测在Win11环境下表现得更BUG。

后续版本的NanUI中如果采用DirectComposition API的话或许会让这种效果回归，当然，我还得先搞定CEF的AcceleratedPaint
