### ISSUE TITLE
cef默认不支持video标签的mp4，mp3 的播放

### ISSUE THREAD

**Issue by thm1118** [NetDimension/NanUI#19]
能发布一个支持mp4，mp3的cef release 吗

**Comment by XuanchenLin** [comment]
抱歉，暂时不能。因为没有稳定的VPN去下载CEF的源代码，因此无法编译出带特定功能的CEF，这点一直都比较头疼。

**Comment by thm1118** [comment]
我现在编译了一个，下载16G，编译了4个小时。
![51test](https://cloud.githubusercontent.com/assets/3632180/23641532/763005d4-032f-11e7-8b8f-0425a4979c44.png)

**Comment by XuanchenLin** [comment]
可以呀，劳驾了。
xuanchenlin(at)msn.com

**Comment by ckhker** [comment]
怎么才能自己编译支持MP4的版本?我这有高速VPN,因为不能MP4我都想转NW.JS了

**Comment by thm1118** [comment]
刚看到，我现在发你邮箱

**Comment by shadow0162** [comment]
@thm1118 我也需要一份，能分享一下吗？gamehope#gmail.com

**Comment by ckhker** [comment]
@thm1118 能发一份吗?联系不上, 661753(at)qq.com

**Comment by shadow0162** [comment]
490586131加群QQ，文件共享里面有

**Comment by zhujinhu21** [comment]
@thm1118 能我发我一份吗? zhujinhu21@163.com  
或者有介绍怎么编译cef支持mp3的吗

**Comment by plainheart** [comment]
@thm1118 同求，非常感谢！最近一直苦于这个！

**Comment by thm1118** [comment]
上面有QQ群啊

**Comment by plainheart** [comment]
谢谢，不过最后解决了。

**Comment by 2033723741** [comment]
cef_binary_3.3239.1723
链接：https://pan.baidu.com/s/1IQvm2uhD9LSlwp9YN07gGw 提取码：dt5n

**Comment by samqy** [comment]
我也遇到cef不能使用video标签，

**Comment by Enemy-8277** [comment]
@thm1118 上面群号搜不到了，可以发一下邮箱吗，求求了。1914118343@qq.com
