### ISSUE TITLE
[REQUEST] 建议使用miniblink内核

### ISSUE THREAD

**Issue by imxcstar** [NetDimension/NanUI#190]
建议使用miniblink内核，也是基于chromium内核，大小会小很多，https://github.com/weolar/miniblink49

**Comment by XuanchenLin** [comment]
这个可以看之前的议题，使用MiniBlink的方案已经被否决。

首先，miniblink确实做到了精简CEF内核的目标，但是也整由于精简了内核导致很多功能被阉割，比如硬件加速，比如视频音频播放等；

其次，miniblink为了兼容XP所以任然在使用非常古老的Chromium 49核心，所导致的就是对JavaScript新API的支持非常差，而且在渲染的定义上也和新标准有所差别。

再次，miniblink对于C#的封装并非官方，从NanUI的QQ群友那儿得到的反馈是并不稳定。

最后，我个人不赞同miniblink推出的VIP API这种做法。
