### ISSUE TITLE
[REQUEST] 是不是可以专门提取一个ChromeBrowser库出来?

### ISSUE THREAD

**Issue by 527395632** [NetDimension/NanUI#193]

**Comment by XuanchenLin** [comment]
这个以后再说，先把这届用CefGlue为核心的NanUI搞定。所以目前是没有时间、精力和财力再弄个项目来维护着的。况且NanUI不稳定的话，做个浏览器控件出来NanUI存在的问题浏览器控件同样存在。

0.8版NanUI现在还存在以下比较严重的问题
- JavaScriptBridge是有bug的
- 资源释放是有问题的，特别是多次跳转页面或者多次刷新页面后内存暴涨。

即将发布的0.9版有待解决这两个问题，如果0.9版能稳定运行，我再考虑把NanUI浏览器相关的核心技术剥离出来弄个浏览器控件。
