### ISSUE TITLE
在 FormiumClient 示例里没有找到关于js 执行 C# 异步返回函数的示例

### ISSUE THREAD

**Issue by sudongg** [NetDimension/NanUI#195]
**NanUI/Formium版本**
0.8.8

**操作系统 / Windows Version**
win 10 1903

**问题描述 / QUESTION**
FormiumClient 示例里只有C# 异步执行 js 带有返回值函数的示例，没有 js 执行 C# 异步带有返回值函数的示例，并且我在FormiumClient 示例 DemoWindowJavaScriptExtension.cs 里找到了 HelloAsync 函数，但是 FormiumClient 示例并没有在 js 里使用这个函数， 请问我在 js 里应该怎么调用这个 HelloAsync ？直接 alert 这个函数返回值是一个 object。

**Comment by XuanchenLin** [comment]
Welcome to 0.9.90

**Comment by sudongg** [comment]
源码似乎没上传。

**Comment by XuanchenLin** [comment]
还在做示例的源码，做好了会放出来。现在代码在私有仓库里。

**Comment by XuanchenLin** [comment]
源码已发布，demo里有异步JS的介绍，感谢关注。

**Comment by sudongg** [comment]
暂时先关闭这个问题，当前项目里用的nanui 0.8 版本，已经被我改了5 6成， 新版0.9改动过大，目前还在考虑要不要更新到新版。

**Comment by XuanchenLin** [comment]
> 暂时先关闭这个问题，当前项目里用的nanui 0.8 版本，已经被我改了5 6成， 新版0.9改动过大，目前还在考虑要不要更新到新版。

嗯，0.9的JavaScript Bridge基本重新写了，目前测试下来比较稳定，之前注册对象的时候嵌套对象注册就有bug，新版已解决。后面我再研究研究，怎么让C#的异步直接绑定到Promise上，如果成功了那么使用js将更加方便。
