### ISSUE TITLE
XP, Win7下会出现系统原生的图标或边框

### ISSUE THREAD

**Issue by Aaronshr** [NetDimension/NanUI#2]
使用NanUI制作软件后运行在xp，win7下偶会出现对应系统的图标或边框（Html设置的页面样式无法覆盖），比如最大化最小化关闭按钮

**Comment by XuanchenLin** [comment]
在重绘非客户区的时候已经处理过0x00ae和0x00af消息，还会出现这个问题？

**Comment by Aaronshr** [comment]
是的，不知道其他人有没有这个问题还是我这个个例

**Comment by XuanchenLin** [comment]
经过测试，WinXP 32位、64位以及Win7 32位和64位都没有出现上述问题。请确定下载的Release是最新的0.3.2版本。
