### ISSUE TITLE
CEF.X64运行时库链接地址错误

### ISSUE THREAD

**Issue by ljf1239848066** [NetDimension/NanUI#20]
http://www.ohtrip.cn/NanUI/NanUIPackages/3.2526.1373/x64/cef_x64.exe

**Comment by XuanchenLin** [comment]
可以访问的嘛

**Comment by nitago** [comment]
有没有一个主目录，可以下载各版本的。比如
http://www.ohtrip.cn/NanUI

**Comment by XuanchenLin** [comment]
@nitago NanUI使用特定版本的CEF，所以放多个版本没有必要。而且可能下次更新的NanUI将移除远程下载CEF库的功能。

**Comment by XuanchenLin** [comment]
已解决
