### ISSUE TITLE
[问题]这个和electron开发有什么区别，我看了下安装也是特别的大，而且更新也不好更新

### ISSUE THREAD

**Issue by weitemi** [NetDimension/NanUI#204]
**NanUI/Formium版本**
**NanUI/Formium Version**

**操作系统 / Windows Version**

**问题描述 / QUESTION**
这个和electron开发有什么区别，我看了下安装也是特别的大，而且更新也不好更新

**Comment by XuanchenLin** [comment]
> **NanUI/Formium版本** **NanUI/Formium Version**
> 
> **操作系统 / Windows Version**
> 
> **问题描述 / QUESTION** 这个和electron开发有什么区别，我看了下安装也是特别的大，而且更新也不好更新

Electron针对JavaScript开发人员，NanUI针对.NET开发者。
