### ISSUE TITLE
内核版本如何升级

### ISSUE THREAD

**Issue by nitago** [NetDimension/NanUI#21]
当前CEF运行库版本：3.2526.1373.gb660893 过低，应该怎么升级？

**Comment by XuanchenLin** [comment]
要升级需要自己编译ChromiumFX代码，然后再根据ChromiumFX和CEF的版本重新编译NanUI。

**Comment by XuanchenLin** [comment]
详细方法请参考ChromiumFX的相关文档。[https://bitbucket.org/chromiumfx/chromiumfx/wiki/Project](https://bitbucket.org/chromiumfx/chromiumfx/wiki/Project)
