### ISSUE TITLE
[问题]-能在netcore api 使用么

### ISSUE THREAD

**Issue by Mrzhangxiaobai2107** [NetDimension/NanUI#212]
我想通过本地资源请求本地接口，能实现么？如果可以如何配置

**Comment by XuanchenLin** [comment]
本地接口指的是啥？asp.net core api吗？这个没有问题的，你可以手动启一个asp.net core的server，也可以从nanui的进程里面来启动。

**Comment by Mrzhangxiaobai2107** [comment]
asp.net core api 怎么配置NanUI
