### ISSUE TITLE
[问题]请问是否有在ui里嵌入winform 或者 wpf 控件的解决方案呢?

### ISSUE THREAD

**Issue by ananck** [NetDimension/NanUI#213]
nanui开发纯页面的时候确实挺不错 但是有些时候我想嵌入一些 winform 或者 wpf的控件的时候 不知道应该怎么处理 请问是否有这方面的解决方案呢? 我想 嵌入个浏览器控件怎么弄?

**Comment by XuanchenLin** [comment]
等我假期的另外一个项目 NanBrowser
