### ISSUE TITLE
请问：html5本地数据库(sqlite），cookie等文件存在在哪个目录？

### ISSUE THREAD

**Issue by nitago** [NetDimension/NanUI#22]
求目录地址，谢谢！

**Comment by XuanchenLin** [comment]
%appdata%\Net Dimension Studio\NanUI\[YOUR APP NAME]

**Comment by XuanchenLin** [comment]
%appdata%\Net Dimension Studio\NanUI\[YOUR APP NAME]

**Comment by XuanchenLin** [comment]
%appdata%\Net Dimension Studio\NanUI\\[YOUR APP NAME]
