### ISSUE TITLE
窗口置顶功能

### ISSUE THREAD

**Issue by programmer-fly** [NetDimension/NanUI#226]
![image](https://user-images.githubusercontent.com/26021587/154252467-51bb7a75-97f9-4892-b0fa-77af4058abb5.png)

像微信这种可以指定，操作其他应用不影响

**Comment by programmer-fly** [comment]
winform本身有这功能的，您那边可以把相关方法和属性暴露出来。https://social.microsoft.com/Forums/zh-CN/09f1343d-9827-4978-914f-bad8f499356a/22914203093577432622winform31383203073262239030?forum=visualcshartzhchs

**Comment by XuanchenLin** [comment]
https://github.com/NetDimension/NanUI/blob/master/src/NetDimension.NanUI/Formium/Formium.HostWindow.cs#L254

`TopMost`属性默认是公开的。
