### ISSUE TITLE
[REQUEST] 有没有可能 整合 HTML-Renderer 作为渲染引擎。

### ISSUE THREAD

**Issue by sgf** [NetDimension/NanUI#237]
**你的想法 / Your idea...**

https://github.com/ArthurHub/HTML-Renderer

如果整合这个的话，那么脱离CEF后感觉应该会好不少吧。
当然，有利有弊， HTML-Renderer 本身的实现质量 并不是那么完美。至少不能和主流浏览器相提并论。
但是有一个，或许js这块直接可以扔掉，从而直接用C#作为脚本。

**Comment by XuanchenLin** [comment]
似乎这个项目很久没更新了，目前nanui使用cef作为渲染内核，目标是使用chromium浏览器的所有渲染特性。当然也就继承了cef体积大占内存的缺陷。如果能找到更合适的渲染引擎必然是未来更好的选择。
