### ISSUE TITLE
[BUG]JS扩展System.NullReferenceException

### ISSUE THREAD

**Issue by zhouge870103** [NetDimension/NanUI#251]
**BUG描述 / Describe the bug**
JS扩展提示System.NullReferenceException:“Object reference not set to an instance of an object.”

**BUG如何产生的 / To Reproduce:**
```
jwb.openFolderDialog({
        title: "请选择保存路径",
        success: function (data) {
          console.log(data);
        },
      });
```
**截图 / Screenshots**
![1650884944(1)](https://user-images.githubusercontent.com/13454176/165077600-d6ee0536-b086-4cdf-b754-cd9d5a8c9e35.png)

**系统环境 / Desktop :**
 - OS: [e.g. Windowx 10]
 - Version [e.g. 1809]

**异常信息 / Thrown Excpetion:**
System.NullReferenceException:“Object reference not set to an instance of an object.”

**Comment by XuanchenLin** [comment]
抱歉，我没有一次性把2个问题看完就急于发布了，这个问题在 NuGet 的 [0.9.90.130](https://www.nuget.org/packages/NetDimension.NanUI/0.9.90.130) 解决。
