### ISSUE TITLE
能不能支持视频播放啊

### ISSUE THREAD

**Issue by mghcool** [NetDimension/NanUI#256]
**NanUI/Formium版本：0.9.90** 

**操作系统 / Windows 10**

**问题描述 ：** nanui好像不支持视频播放，有什么方法开启吗？

**Comment by XuanchenLin** [comment]
默认的CEF包是不支持h264格式的视频（也就是常说的mp4视频）。

需要自行编译CEF源码并在编译前加上支持视频播放的编译符号，编译CEF的方法可以参考：https://bitbucket.org/chromiumembedded/cef/wiki/MasterBuildQuickStart.md

如果懒得自己编译可以考虑赞助NanUI项目399元获得现成的可以支持视频播放的CEF包，请参考：
https://github.com/NetDimension/NanUI#%E7%89%B9%E5%88%AB%E8%B5%9E%E5%8A%A9
