### ISSUE TITLE
'Newtonsoft.Json.Linq.JObject' does not contain a definition for 'Uuid'

### ISSUE THREAD

**Issue by zhouge870103** [NetDimension/NanUI#257]
**BUG描述 / Describe the bug**
**此BUG不影响使用**
引发了异常: Microsoft.CSharp.dll 中的“Microsoft.CSharp.RuntimeBinder.RuntimeBinderException”(“'Newtonsoft.Json.Linq.JObject' does not contain a definition for 'Uuid'”) 引发了异常: Microsoft.CSharp.dll 中的“Microsoft.CSharp.RuntimeBinder.RuntimeBinderException”(“'Newtonsoft.Json.Linq.JObject' does not contain a definition for 'Uuid'”)

**BUG如何产生的 / To Reproduce:**
第一次调用原生方法时发生

**截图 / Screenshots**
![1652030524(1)](https://user-images.githubusercontent.com/13454176/167307843-e4d30d1e-747d-4fb0-ad46-268aa634067a.png)

**系统环境 / Desktop :**
 - OS: [e.g. Windowx 10]
 - Version 0.9.90.130

**异常信息 / Thrown Excpetion:**

**Comment by XuanchenLin** [comment]
感谢，请问能否提供复现此问题的代码？

**Comment by XuanchenLin** [comment]
因为缺少更详细的信息，因此无法复现此问题。
