### ISSUE TITLE
web 页面中调用winform中的方法后，怎么获取到方法的返回值

### ISSUE THREAD

**Issue by zhujinhu21** [NetDimension/NanUI#26]
//在js中注册一个方法
GlobalObject.AddFunction("readCard").Execute += (sender, args) =>
{
          //把读卡获取到身份证的信息返回
         

 return "身份证"； 
};

直接return 报错，下图中123,456是模拟读卡后的结果

![qq 20170712104550](https://user-images.githubusercontent.com/4327149/28099555-c8bda13e-66ef-11e7-9f76-d10fb4072225.png)

**Comment by fiveyoung** [comment]
CfrV8Value returnValue = CfrV8Value.CreateString("123,456");
args.SetReturnValue(returnValue);
