### ISSUE TITLE
支持 aot 发布？

### ISSUE THREAD

**Issue by sudongg** [NetDimension/NanUI#263]
我尝试使用aot 发布，但无法运行，是否能支持aot 发布？

**Comment by XuanchenLin** [comment]
单文件发布需要手动指定CEF运行时文件的路径，自动打包不会打包cef支持文件

**Comment by sudongg** [comment]
我指的是  .NET NativeAOT  发布，不是普通的单文件发布。
参考：
https://baijiahao.baidu.com/s?id=1693096922730979706&wfr=spider&for=pc

NativeAOT  发布后C#代码生成原生库，并且能大幅减少启动时间。

**Comment by XuanchenLin** [comment]
抱歉，这个没有研究过，所以不好判断AOT发布后启动不了的具体原因是什么，如果方便请提供 Windows 事件查看器中应用启动时的错误信息。
