### ISSUE TITLE
关于窗口移动的问题

### ISSUE THREAD

**Issue by 527395632** [NetDimension/NanUI#267]
项目示例中, 窗口"TitleBar"的拖动非常流畅, 然后查阅文档没有说到如何实现拖动。但是有关于设置窗口位置的api.我使用moveTo方法设置窗口后效果很不理想, 鼠标经常移出“TitleBar”之外导致拖动不响应, 想问一下这个窗口拖动是如何实现的?

**Comment by SamWangCoder** [comment]
可以仿照这个  通过样式控制拖动
![image](https://user-images.githubusercontent.com/45822556/173968642-1010e692-ab5e-4211-8d92-323ad2fc1a8a.png)
``` html
<div class="bg-success" style="-webkit-app-region: drag">
  <div class="bg-warning" style="-webkit-app-region: no-drag; margin: 0 30px;">禁止拖动区域</div>
</div>
```
``` css
div {
  -webkit-app-region: drag;
}
```

**Comment by XuanchenLin** [comment]
可以参考下B站上面的这两个视频：

https://www.bilibili.com/video/BV1j34y1B7fs/?vd_source=17b7aca52158823ec8a1fc452dde7dbf

https://www.bilibili.com/video/BV1eS4y1Z7p2/?vd_source=17b7aca52158823ec8a1fc452dde7dbf
