### ISSUE TITLE
js调用c#方法，如何实现非阻塞调用

### ISSUE THREAD

**Issue by dxp909** [NetDimension/NanUI#27]
js调用一个耗时的c#方法，UI就阻塞了，如何实现非阻塞调用

**Comment by dxp909** [comment]
还有如何传递参数呢

**Comment by fiveyoung** [comment]
我是这样处理的：js调用C#的函数，传递一个回调函数名给C#方法，C#方法内部使用异步处理数据，处理完成后调用HtmlUIForm的ExecuteJavascript方法调用js函数，并将结果转成json作为参数传过去。然后js再显示到界面上。

**Comment by fiveyoung** [comment]
JSObject.AddFunction("showDevTools").Execute += (sender, e) =>
{
    e.Arguments[x];//获取js传过来的参数
    e.SetReturnValue(xxxxxx);//返回结果给js
};

**Comment by dxp909** [comment]
ok，tks

**Comment by zhujinhu21** [comment]
@dxp909  js调用客户端事件 ui阻塞 你是怎么解决的

**Comment by dxp909** [comment]
@zhujinhu21 您说的客户端事件是指的什么？

**Comment by zhujinhu21** [comment]
就是调用winform中的方法 ，我的方法功能是读卡，时间长了点要3,4秒

**Comment by dxp909** [comment]
@zhujinhu21 ,就是按照 @fiveyoung 提供的方法：传递一个回调函数名给C#方法，C#方法内部使用异步处理数据，处理完成后调用HtmlUIForm的ExecuteJavascript方法调用js函数，并将结果转成json作为参数传过去。然后js再显示到界面上

**Comment by XuanchenLin** [comment]
使用回掉函数来实现，具体看CEF的文档。https://bitbucket.org/chromiumembedded/cef/wiki/JavaScriptIntegration#markdown-header-using-js-callbacks
