### ISSUE TITLE
[问题] 很奇怪的问题，按照官方的例子，调用C#代码 ，提示 [NanUI]: Promise is not exits.

### ISSUE THREAD

**Issue by a531246041** [NetDimension/NanUI#281]
**NanUI/Formium版本**
**NanUI/Formium Version**
![image](https://user-images.githubusercontent.com/33302476/194372858-1ab8d041-9d8c-48f4-a4e7-cc1352a2eea9.png)

**操作系统 / Windows Version**

**问题描述 / QUESTION**

**Comment by XuanchenLin** [comment]
确定下NuGet安装的版本，直接启用Promise返回值是最后这个版本才加上的。

**Comment by XuanchenLin** [comment]
无反馈就关了吧
