### ISSUE TITLE
速度慢

### ISSUE THREAD

**Issue by Aaronshr** [NetDimension/NanUI#3]
目前如果软件是首次使用会出现软件启动速度慢，绘制页面慢（软件起来了，页面还没显示，空白），非首次不会出现这些问题

**Comment by XuanchenLin** [comment]
@Aaronshr 这个问题在WinXP的虚拟机上出现过，暂时不晓得是哪里的问题。

**Comment by Aaronshr** [comment]
我在win10下也是，只要是首次安装或使用软件就会出现，之后就不会有了

**Comment by XuanchenLin** [comment]
@Aaronshr 你是说软件的启动速度还是下载器下载框架的速度？

**Comment by XuanchenLin** [comment]
设置SplashImage和SplashBackColor来规避加载白屏的问题。
