### ISSUE TITLE
[REQUEST] 自定义错误页面

### ISSUE THREAD

**Issue by 312977** [NetDimension/NanUI#312]
如果加载页面失败 ，则会跳转到 nanui错误页面，页面上有 
 nanui 内部错误，目标地址无法访问，请重新指定地址，
麻烦能让修改这个页面 或者 修改任何显示文字内容

**Comment by XuanchenLin** [comment]
新的代码里在 LoadEnd 事件中加上了 SkipErrorHandler 属性用来指示在发生页面无法访问时是否调用 NanUI 内部的错误页面，设置为 true 跳过内部错误页面的显示。

另外还加上了 ErrorPageUrl 属性用来在发生页面无法访问时跳转到指定的 url 上，需要注意的是这个属性需要 SkipErrorHandler 为 false 时才有效果。
