### ISSUE TITLE
[BUG] 错误页面无法通过 LoadError 自定义错误

### ISSUE THREAD

**Issue by 312977** [NetDimension/NanUI#313]
LoadError 我理解可以在加载错误后，自定义后续操作，然后并不能。一下代码不工作，还是跳转到错误页面去了
this.LoadError += LoadErrorPage;

private void LoadErrorPage(object sender, EventArgs e)
        {
            Task.Run(async () =>
            {
                await Task.Delay(5000);
                base.LoadUrl("https://www.baidu.com");
            });
        }
如果加载页面失败 ，则会跳转到 nanui错误页面，页面上有 
 nanui 内部错误，目标地址无法访问，请重新指定地址，

**Comment by XuanchenLin** [comment]
同上一个问题 #312
