### ISSUE TITLE
编译错误 HtmlUIForm 351行

### ISSUE THREAD

**Issue by 2033723741** [NetDimension/NanUI#32]
我查看了以前的历史代码，正确应该是下面：
IntPtr chromeWidgetHostHandle = IntPtr.Zero;
						if (BrowserWidgetHandleFinder.TryFindHandle(BrowserHandle, out 
 chromeWidgetHostHandle))
						{
							messageInterceptor = new BrowserWidgetMessageInterceptor(browser, chromeWidgetHostHandle, OnWebBroswerMessage);
							break;
						}
						else
						{
							System.Threading.Thread.Sleep(100);
						}

**Comment by XuanchenLin** [comment]
@2033723741 C#7.0新语法，不解释。
