### ISSUE TITLE
[问题]如何设置为单进程

### ISSUE THREAD

**Issue by zcfeng7014** [NetDimension/NanUI#336]
程序运行后，进程管理器中发现多个进程。
因为程序入口，做了一些吃性能的操作，多进程会严重占用系统资源。

**Comment by XuanchenLin** [comment]
跟浏览器一样 CEF 采用多进程架构，不同的进程负责不同的工作内容：比如图形渲染，JavaScript，网络通信等等都是由其子进程来处理的，因此无法设置为单进程。
