### ISSUE TITLE
播放视频文件 时效率有点低，内存CPU和NW完全没法比

### ISSUE THREAD

**Issue by ckhker** [NetDimension/NanUI#34]
播放视频文件 时效率有点低，内存CPU和NW完全没法比
不知道是什么原因
![qq 20170830015319](https://user-images.githubusercontent.com/11842607/29836118-d1594980-8d26-11e7-9bac-a499a742f4c6.png)

**Comment by XuanchenLin** [comment]
不晓得您是如何做的对比，播放的是什么样的视频。
nanui基于ChromiumFX，ChromiumFX作为CEF的.net wrapper，通过PInvoke的方式来调用CEF相关接口，效能上确实比不过原生C++开发的nwjs，这一点无法进一步优化。

**Comment by XuanchenLin** [comment]
没有回馈，关闭。
