### ISSUE TITLE
[BUG]fullscreen的时候，无法返回

### ISSUE THREAD

**Issue by andisk** [NetDimension/NanUI#349]
**BUG描述 / Describe the bug**
当页面申请全屏的时候，无法退出全屏。

**BUG如何产生的 / To Reproduce:**

**截图 / Screenshots**

**系统环境 / Desktop :**
 - OS: [e.g. Windowx 10]
 - Version [e.g. 1809]

**异常信息 / Thrown Excpetion:**

**Comment by XuanchenLin** [comment]
这个不是BUG，操作不当，我已经远程帮解决了。
