### ISSUE TITLE
打开子窗体，页面空白，但如果把父窗体隐藏后，子窗体显示就正常

### ISSUE THREAD

**Issue by dxp909** [NetDimension/NanUI#35]
资源已经设置为嵌入资源

**Comment by XuanchenLin** [comment]
经过测试，并没有出现上述问题，请问什么版本？代码帖上来一窥？

**Comment by dxp909** [comment]
问题已经解决，打开窗口的时候用这样的方式ShowDialog(new HtmlUIForm())，以前打开的时候，ShowDialog参数没有设置

**Comment by XuanchenLin** [comment]
嗯，那就关闭吧。
