### ISSUE TITLE
降到0.4版本后页面空白

### ISSUE THREAD

**Issue by dxp909** [NetDimension/NanUI#39]
开始使用的是0.5版本，为了兼容XP，就降到了0.4版本，这个时候启动程序就成了空白了，然后再还原回去，也不行了，请求帮助
另外升级到0.6版本，问题依旧，是不是哪里配置出现问题了

**Comment by dxp909** [comment]
找到问题原因，发布的exe名称必须跟默认命名空间保持一致，否则就出现了上述问题，可以考虑在后续版本中解决这样的场景

**Comment by XuanchenLin** [comment]
请使用0.6
