### ISSUE TITLE
如何显示一个网络图片

### ISSUE THREAD

**Issue by dxp909** [NetDimension/NanUI#40]
我是用img标签显示一个网络图片，https协议下可以，但是http协议下不行，通过浏览器访问都是可以访问到的，使用的版本是0.5

**Comment by XuanchenLin** [comment]
本地测试没出现过这个问题，请详细描述问题产生的条件和环境。

**Comment by dxp909** [comment]
场景是这样的，页面上有一个按钮，点击后，调用C#服务方法去读取数据库数据，获取一张图片地址，读取完后再调用一个js方法，这个js方法里逻辑很简单，就是把c#读取到的图片通过$("img").attr("src","路径")的方式修改图片路径，但是设置后，图片始终不显示，我通过alert也能够弹出路径信息

**Comment by dxp909** [comment]
问题已经找到，不是框架的原因
