### ISSUE TITLE
请问，如果页面上有一个<input type=file/>，c#如何接收选择的文件

### ISSUE THREAD

**Issue by dxp909** [NetDimension/NanUI#41]

**Comment by shenlanchenwei** [comment]
其实你不需要这样,你只需要通过JS来调用C#代码打开文件选择就可以了,这个标签和在浏览器里用的效果是一样的,C#那边应该获取不到文件

**Comment by XuanchenLin** [comment]
可以自定义requesthandler来接收文件，或者如上面朋友说的，在js环境里注册C#的方法来接收文件。
