### ISSUE TITLE
关于数据绑定

### ISSUE THREAD

**Issue by ywxt** [NetDimension/NanUI#42]
可不可以实现像https://github.com/NeutroniumCore/Neutronium
这样的数据绑定？

**Comment by XuanchenLin** [comment]
非常不错的项目，但是与VUE深度整合可能导致其他一些不使用VUE的项目工作不正常，我正在思考用那种方式来更好注入C#对象并且减轻对框架的依赖。

**Comment by ywxt** [comment]
那HTML上的数据绑定可不可以自己写一个，而不用依赖于整个Vue？

**Comment by ywxt** [comment]
@XuanchenLin
再问一下，NANUI有实现跨平台的计划吗？目前.NET的一些CEF项目好像还没有迁移到.NET CORE上。

**Comment by XuanchenLin** [comment]
@ywxt dot net core没有任何界面的实现，所以移植.net core是不可能的。倒是有移植到mono的可能。
