### ISSUE TITLE
Do you have a plan to make a vue bind version

### ISSUE THREAD

**Issue by mrtylerzhou** [NetDimension/NanUI#44]
NanUi is awesome for winform lovers.Do you have a plan to a vuejs bind version?So it is easier to use vue ecosystem resources and viewmodels

**Comment by XuanchenLin** [comment]
之前有朋友推荐了https://github.com/NeutroniumCore/Neutronium 这个项目，这个项目用vue实现了数据的双向绑定，可以参考。目前NanUI暂时没有使用VUE做数据绑定的计划，但是会有相应的替代方案来直接注册C#对象，直接使用C#对象注册的话可以减少对框架的依赖，而不是仅仅局限于某个框架。

**Comment by mrtylerzhou** [comment]
谢谢回复,我看了那个项目,但是好像是wpf的,现在项目中没有用到桌面框架,平时自己做一些桌面项目,wpf不是很熟,还是更喜欢winform成型快.好吧,希望这个项目越来越好,有时间了也会看看大神的代码,期望自己也能贡献些代码

**Comment by XuanchenLin** [comment]
感谢支持。
