### ISSUE TITLE
使用bootstrap.css时程序会停止工作

### ISSUE THREAD

**Issue by lyuyifei** [NetDimension/NanUI#47]
把bootstrap.css作为嵌入的资源，再调用Chromium.ShowDevTools();方法，程序会崩溃。
使用的0.6版本nanui，测试demo BorderlessFormStyleDemoApp项目中index.html 添加 link href="styles/bootstrap.css" rel="stylesheet" ，运行程序，拖动devtools就会抛出为捕获异常。

引用空白的bootstrap.css文件不会有问题，可能里面什么样式有问题

0x0F569A2A (libcfx.dll)处(位于 BorderlessFormStyleDemoApp.exe 中)引发的异常: 0xC0000005: 读取位置 0x00000008 时发生访问冲突。

**Comment by XuanchenLin** [comment]
感谢提交问题，这是因为XP的依赖项里面打包打错了个文件，请更新依赖项到最新版本来解决这个问题。

**Comment by lyuyifei** [comment]
测试发现 bootstrap.css 文件中 /*# sourceMappingURL=bootstrap.css.map */ 等注释删除掉，就不会抛出异常。。原因不明。作者已发布新版本，准备更新依赖项使用，如果仍然遇到此问题，打算删除掉注释使用，忽略此问题。
