### ISSUE TITLE
窗体置顶问题

### ISSUE THREAD

**Issue by zgcwkj** [NetDimension/NanUI#58]
Show出的子窗体永远置顶，按道理来说Show的窗体单击时置顶显示，点击另一个时那么另一个置顶显示

复现：
父窗体，Show（不是ShowDialog）一个子窗体
单击父窗体时，子窗体还是置顶显示，父窗体被遮挡

**Comment by XuanchenLin** [comment]
SomeChild.Show(this);
这样的话，Child永远在父窗体前面。

**Comment by zgcwkj** [comment]
@XuanchenLin 已解决，原来是我传递了父窗体的问题。。。
