### ISSUE TITLE
.net 4 client profile语法问题

### ISSUE THREAD

**Issue by qq362220083** [NetDimension/NanUI#6]
你好，

      感谢提供开源的UI框架。我发现代码中使用了一部分c# 6.0的新特性，而我使用vs2012编译，每次下载之后都要手动修改一遍语法，希望作者能改为c# 5.0大众语法，谢谢

**Comment by XuanchenLin** [comment]
新版VS发布在即，编程也需要跟上时代的步伐。VS2015转瞬即逝，既然如此何不顺应时代潮流？因此在这个问题上不会妥协。如果无法编译直接下载Release引用使用，感谢支持！
