### ISSUE TITLE
本来想增加程序健壮性,却出现莫名bug

### ISSUE THREAD

**Issue by mrtylerzhou** [NetDimension/NanUI#61]
js调用c#方法时,对原来代码加上逻辑判断比如(e.arguments[0].IsValid(),IsInt,IsString)等判断,本想这样程序可能会更健壮一些,却往往在第一次执行的时候抛出"数组超出边界"异常,并且会导致页面卡死.(我的版本是旧的,不知道作者是否对此做过更正呢)

**Comment by XuanchenLin** [comment]
为何不先判断argument的对象数量呢？上述写法在arguments的length为0时必然报错啊。

**Comment by mrtylerzhou** [comment]
已经判断了,我截取的只是部分,问题出现在isvalid(),isint这些函数有时候会出现异常

**Comment by mrtylerzhou** [comment]
比如a=arguments[0]
a.isValid()//是在这一行报错的,但是不是每次都报错

**Comment by XuanchenLin** [comment]
请参考文章知乎专栏[NanUI 技术内幕](https://zhuanlan.zhihu.com/nanui)
