### ISSUE TITLE
Bootstrap.Load(PlatformArch.x86)

### ISSUE THREAD

**Issue by JoyNop** [NetDimension/NanUI#64]
Bootstrap.Load(PlatformArch.x86)

无法指定？？

新版本如何操作哇

**Comment by XuanchenLin** [comment]
[WIKI](https://github.com/NetDimension/NanUI/wiki)

请仔细阅读文档。

**Comment by XuanchenLin** [comment]
请参考文章知乎专栏[NanUI 技术内幕](https://zhuanlan.zhihu.com/nanui)
