### ISSUE TITLE
能不能动态加载本地图片

### ISSUE THREAD

**Issue by scwyh** [NetDimension/NanUI#65]
页面中显示的图片都是采用嵌入式的，现在需要能根据需要动态加载图片，测试了可以动态加载网络上远程的图片。但是，项目中的图片比较大，想先存在本地，再循环显示，可能，测试了一下，不能动态载本地图片。有什么方法可动态加载本地图片？

**Comment by aochulai** [comment]
先Bootstrap.RegisterFolderResources(“D:\\views”, “http://local.ui”);
把图片保存到本地：d:\\views\img.png;
然后html里就可以<img src="http://local.ui/img.png“/>这样了

**Comment by xuzeyu91** [comment]
可以以文件的形式存在目录，读取时用c#转码成base64

**Comment by XuanchenLin** [comment]
支持的，请参考知乎专栏[NanUI 技术内幕](https://zhuanlan.zhihu.com/nanui)中有关于资源处理器的章节。
