### ISSUE TITLE
libcef.dll is not found 存在这个dll，还是一直报错

### ISSUE THREAD

**Issue by XinUniverse** [NetDimension/NanUI#69]
libcef.dll is not found

**Comment by XuanchenLin** [comment]
这个是CEF的版本不对，请更新Nuget包

**Comment by 80Arrow** [comment]
> libcef.dll is not found

可以解决吗？

**Comment by XuanchenLin** [comment]
请参考知乎专栏[NanUI 技术内幕](https://zhuanlan.zhihu.com/nanui)
