### ISSUE TITLE
下载文件

### ISSUE THREAD

**Issue by kaiyangyang** [NetDimension/NanUI#70]
DownloadHandler.OnBeforeDownload += (sender, e) => { e.Callback.Continue("", true); };用于下载时选择文件保存路径，系统自动下载
DownloadHandler.OnDownloadUpdated用于处理文件下载进度

**Comment by yozochen** [comment]
为什么<a href="http://res.app.local/text.txt" download="sdfsd.txt" target="_blank" >下载</a>不会出发这个DownloadHandler.OnBeforeDownload这个事件？
