### ISSUE TITLE
关于localstorage的问题

### ISSUE THREAD

**Issue by kelyljk** [NetDimension/NanUI#73]
能发调整localstorage的存储上限

**Comment by XuanchenLin** [comment]
与CEF同样的配置，启动时使用disk-cache-size参数来设置缓存大小。
具体请参考
[https://peter.sh/experiments/chromium-command-line-switches/](https://peter.sh/experiments/chromium-command-line-switches/)

**Comment by XuanchenLin** [comment]
请参考文章知乎专栏[NanUI 技术内幕](https://zhuanlan.zhihu.com/nanui)
