### ISSUE TITLE
文件下载

### ISSUE THREAD

**Issue by fl0922** [NetDimension/NanUI#74]
下载文件如何实现呢？貌似正常的下载方式无法使用了

**Comment by yozochen** [comment]
是呀，同问，如何下载？

**Comment by XuanchenLin** [comment]
使用DownloadHandler里的相关事件处理下载过程。
具体请参考CEF文档。

**Comment by XuanchenLin** [comment]
请参考文章知乎专栏[NanUI 技术内幕](https://zhuanlan.zhihu.com/nanui)
