### ISSUE TITLE
放置一晚上以后会出现白屏

### ISSUE THREAD

**Issue by xuzeyu91** [NetDimension/NanUI#75]
放置一晚上以后会出现白屏，目前这个问题为偶先，不知道是线程被释放还是什么原因导致，出现过很多次，但是不能稳定重现，又解决方法吗？

**Comment by XuanchenLin** [comment]
白屏是渲染进程挂掉导致的，目前无法判断是什么问题导致的白屏。
建议使用RequestHandler的OnRenderProcessTerminated事件里处理渲染进程挂掉后让Browser重新加载当前网页来重启渲染进程。

**Comment by XuanchenLin** [comment]
请参考文章知乎专栏[NanUI 技术内幕](https://zhuanlan.zhihu.com/nanui)
