### ISSUE TITLE
可否直接加载本地 html/css 而无需嵌入到资源文件呢？

### ISSUE THREAD

**Issue by kafka-yu** [NetDimension/NanUI#76]
如题，目前加载本地文件都需要嵌入到 resource 再加载，可否直接加载文件呢？

**Comment by XuanchenLin** [comment]
使用Bootstrap. RegisterFolderResources可以把文件夹注册成资源

**Comment by XuanchenLin** [comment]
请参考文章知乎专栏[NanUI 技术内幕](https://zhuanlan.zhihu.com/nanui)
