### ISSUE TITLE
c#获取js 函数的参数和返回json字符串，非issue，作者的文档也没有说明，只好自己百度找到一些方法

### ISSUE THREAD

**Issue by csabc** [NetDimension/NanUI#77]
返回json字符串参考下面的连接
https://bitbucket.org/chromiumfx/chromiumfx/issues/184/how-to-convert-the-c-object-to-cfrv8value#comment-48503041

js调用c#函数search({bc:"123",store:"456"})

c#定义函数如下：

            GlobalObject.AddFunction("search").Execute +=(_,args)=>{
                var parabc =args.Arguments.FirstOrDefault(p=>p.IsObject).GetValue("bc").StringValue;
                var parastore = args.Arguments.FirstOrDefault(p => p.IsObject).GetValue("store").StringValue;

                List<Potts> potts = new List<Potts>
                {
                    new Potts { PottsId = "1123",StoreId="12345",StoreName="123", Item = "1234567", CommonName = "测试的数", Ena = "1234567989123", Lot = "er2324", Quantity = 12 }
                };

                JToken result = JToken.Parse(JsonConvert.SerializeObject(potts));

                args.SetReturnValue(ToCfrV8Value(result));

            };

        public CfrV8Value ToCfrV8Value(JToken json)
        {
            
            CfrV8Value output = null;
            if (json.Type == JTokenType.Array)
            {
                var arrLength = json.Count();
                output = CfrV8Value.CreateArray(arrLength);
                for (var i = 0; i != arrLength; i++)
                    output.SetValue(i, ToCfrV8Value(json[i]));
            }
            else if (json.Type == JTokenType.Object)
            {
                var accessor = new CfrV8Accessor();

                output = CfrV8Value.CreateObject(accessor);

                var childrens = json.Children();

                foreach (dynamic child in childrens)
                {
                    output.SetValue(child.Name, ToCfrV8Value(child), CfxV8PropertyAttribute.None);
                }
            }
            else
            {
                if (json.Type == JTokenType.Property)
                {
                    var val = ((JProperty)json).Value;
                    var valueType = val.Type;

                    if (valueType == JTokenType.String)
                        output = CfrV8Value.CreateString(val.Value<string>());
                    else if (valueType == JTokenType.Boolean)
                        output = CfrV8Value.CreateBool(val.Value<bool>());
                    else if (valueType == JTokenType.Integer)
                        output = CfrV8Value.CreateInt(val.Value<int>());
                    else if (valueType == JTokenType.Float)
                        output = CfrV8Value.CreateDouble(val.Value<double>());
                    else if (valueType == JTokenType.Null)
                        output = CfrV8Value.CreateNull();
                    else if (valueType == JTokenType.Date)
                        output = CfrV8Value.CreateDate(CfrTime.FromUniversalTime(val.Value<DateTime>()));
                }
            }

            return output;
        }

list 也应该可以直接转CfrV8Value吧，需要修改ToCfrV8Value方法。

**Comment by XuanchenLin** [comment]
请参考文章知乎专栏[NanUI 技术内幕](https://zhuanlan.zhihu.com/nanui)
