### ISSUE TITLE
LifeSpanHandler 如何阻止默认弹窗或者弹出自定义窗体

### ISSUE THREAD

**Issue by kaiyangyang** [NetDimension/NanUI#78]
LifeSpanHandler.OnBeforePopup += LifeSpanHandler_OnBeforePopup;
private void LifeSpanHandler_OnBeforePopup(object sender, Chromium.Event.CfxOnBeforePopupEventArgs e)
        {
        }

**Comment by XuanchenLin** [comment]
参数e的SetReturnValue来控制，具体请参照CEF文档。
