### ISSUE TITLE
Forium没有两个参数的构造方法

### ISSUE THREAD

**Issue by lreach** [NetDimension/NanUI#79]
` public class Formium : ModernUIForm, IChromiumClient
    {
        protected readonly WebBrowserControl BrowserWrapper;

        public Formium();
        public Formium(string initialUrl);

        [Browsable(false)]
        public bool CanGoForward { get; }
        [Browsable(false)]
        public JSObject GlobalObject { get; }
        [Browsable(false)]
        public CfxContextMenuHandler ContextMenuHandler { get; }
        [Browsable(false)]
        public CfxLifeSpanHandler LifeSpanHandler { get; }`

如上，只有无参和一个参数的
而文档里的例子用的是两个的
`public Form1()
			//Load embedded resource index.html and not set form to no border style by the second parameter.
			: base("http://res.app.local/index.html", false)
		{
			InitializeComponent();
		}`
咋弄

**Comment by XuanchenLin** [comment]
API做了一些修改。
如果需要使用系统边框样式，请继承WinFormium类。

**Comment by XuanchenLin** [comment]
请参考文章[运行您的第一个 NanUI 应用程序](https://zhuanlan.zhihu.com/p/109016066)。
