### ISSUE TITLE
win10 最大化窗口位置不对

### ISSUE THREAD

**Issue by jeerisguo** [NetDimension/NanUI#80]
https://www.cnblogs.com/linxuanchen/p/NanUI-Examples-03-Design-Your-Form-With-Html.html

**Comment by jeerisguo** [comment]
使用的这个Demo示例，最大化后 会往上移一条，点击Title 后又正常

**Comment by XuanchenLin** [comment]
目前不同电脑上的系统会有一些莫名奇妙的问题，并不是所有Win10都这样，所以这个需要收集更多信息才能判断是什么问题。

**Comment by XuanchenLin** [comment]
0.7版已解决此问题。
