### ISSUE TITLE
有两个不关闭按钮是哪里配置不对吗？

### ISSUE THREAD

**Issue by servucn** [NetDimension/NanUI#83]
![image](https://user-images.githubusercontent.com/6037332/57928449-5fb33480-78e3-11e9-9265-bedc154f04c6.png)

**Comment by XuanchenLin** [comment]
群里有视频。

**Comment by gygang** [comment]
群名叫什么？

**Comment by XuanchenLin** [comment]
请参考文章[运行您的第一个 NanUI 应用程序](https://zhuanlan.zhihu.com/p/109016066)中的`可能遇到的问题`段落。
