### ISSUE TITLE
支持React前端页面吗

### ISSUE THREAD

**Issue by JoyNop** [NetDimension/NanUI#85]
今天根据sayHello的demo做了一下试验，原生js是可以的，
发现使用create-react-app 脚手架创建前端项目，js和ts版react项目均不能正常调用，可以在nanui中正常浏览，但是winform调用js并没有效果

是因为webpack打包的问题还是其他原因？

以及在react-ts项目中如何正确调用？

```javascript
import * as React from 'react';
import './App.css';


class App extends React.Component {
  public render() {
    return (
      <div className="App">
        4333
        <p id='hello-container'>22</p>
        <button onClick={this.sayHello}>22</button>
  </div>
    );
  }

   private  sayHello=()=> {
     debugger
  var p = document.createElement("p");
  p.innerText = "Hello NanUI!";

  var container = document.getElementById("hello-container");
  container.appendChild(p);
} 
componentDidMount(){ 
}
}

export default App;

```
![TIM图片20190724154230](https://user-images.githubusercontent.com/25074750/61774560-b1b78f80-ae29-11e9-814c-9716b908db76.png)
![TIM图片20190724154236](https://user-images.githubusercontent.com/25074750/61774562-b2502600-ae29-11e9-8d37-df5370221091.png)

![TIM图片20190724153902](https://user-images.githubusercontent.com/25074750/61774442-70bf7b00-ae29-11e9-8a06-f1504c901b3e.png)

![TIM图片20190724153844](https://user-images.githubusercontent.com/25074750/61774440-7026e480-ae29-11e9-803e-312399261d38.png)

**Comment by XuanchenLin** [comment]
webpack打包后js的结构是按照webpack的规则来设立的，所以直接调用是没有办法调用到类的内部的。所以建议把需要调用的js独立到webpack范围外。

**Comment by XuanchenLin** [comment]
最近在有项目用到React，所以现在能够给出明确答案，NanUI注册的对象都挂载在window对象上，所以可以直接在window上调用，例如：
```jsx
componentDidMount() {
  const NanUI = window["NanUI"];
  console.log(NanUI.version);
}
```

**Comment by JoyNop** [comment]
> ```js-jsx
> const NanUI = window["NanUI"];
> ```

感谢，看到回复及时测试了一下，最小化功能正常，并且看了React 的demo，但是没有发现demo中如何通过c# 调用 React 方法，能在demo补充一下吗？

**Comment by JoyNop** [comment]
@XuanchenLin 貌似无法reopen issue  ...

**Comment by hlzfr** [comment]
请问C#调用React的方法解决了吗？我现在也是想C#调用webpack打包的Vue里的方法

**Comment by JoyNop** [comment]
> 请问C#调用React的方法解决了吗？我现在也是想C#调用webpack打包的Vue里的方法

我想C#调用肯定是不行了，webpack打包会重命名，要么去掉重命名，要么吧调用的js单独拿出来，不要打包，或者直接走socket理论也行，不过我今天想了想，好像c#调js的用处好像不是很大，文档中那给回调方法可能会用的多一点。。。
