### ISSUE TITLE
打开窗体时 抛出异常

### ISSUE THREAD

**Issue by Rohmeng** [NetDimension/NanUI#87]
NetDimension.NanUI
Unexpected end of stream.
   在 Chromium.Remote.StreamHandler.FillReadBuffer(Int32 count)
   在 Chromium.Remote.RemoteConnection.ReadLoop()
   在 Chromium.Remote.RemoteConnection.ReadLoopEntry()

**Comment by XuanchenLin** [comment]
cef的路径结果错误。请按照nuget包下载后的fx路径进行部署。

**Comment by Rohmeng** [comment]
fx路径应该是对的，我自己windows10的环境启动一切正常，Windows7 环境软件第一次启动 就会抛出未处理的UI异常，应用直接被强制退出了，再次启动又正常。。。

**Comment by XuanchenLin** [comment]
需要提供更多细节
