### ISSUE TITLE
在win10上打开baidu.com会闪烁

### ISSUE THREAD

**Issue by twtyypmb** [NetDimension/NanUI#89]
桌面上点右键，打开【显示设置】，【缩放与布局】里面，【更改文本、应用等项目的大小】将【100%】改为【125%】，再运行程序，打开baidu.com，会发现html界面会闪烁，点击搜索，仍然闪烁

**Comment by zhangliang2008** [comment]
项目添加应用程序清单文件,然后取消注释
`  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
    </windowsSettings>
  </application>`

**Comment by XuanchenLin** [comment]
请参考文章[运行您的第一个 NanUI 应用程序](https://zhuanlan.zhihu.com/p/109016066)中的`可能遇到的问题`段落。
