### ISSUE TITLE
支持更新

### ISSUE THREAD

**Issue by mrtylerzhou** [NetDimension/NanUI#90]
时隔一年又更新了,希望能持续更新

**Comment by XuanchenLin** [comment]
已重写窗口底层，加入了win10高dpi的支持，优化了代码结构和逻辑。

另外，新版本的NanUI正在加紧开发中。

**Comment by mrtylerzhou** [comment]
我们是国内某快件公司,可能是用nanui比较大的公司了.基于nanui我们做了端的监控平台,端的自动更新,下面计划做端的集中运维工作.由于前些年开始就一直在用,使用的是谷歌内核42,很多新项目支持的不是很好(vue项目大列表直接在浏览器打开正常,在端嵌入的页面里打卡非常卡).本想着借此机会参照nanui自己再做一个开源项目,既然大佬还在坚持继续开发也就放弃自造轮子的计划了.

**Comment by XuanchenLin** [comment]
感谢支持。后面需要收集一些成功案例的信息，如果不涉及侵权的话还请提供案例信息，感激不尽！

**Comment by mrtylerzhou** [comment]
申通快递梧桐客户端,梧桐客户端为申通所有系统的入口.是一个混合开发平台,可以直接挂载web项目,同时也有扫描模块为混合模块,提供了串口通信,调用windows api的原生功能.

**Comment by mrtylerzhou** [comment]
我们在原有的基础上也开发了一些实用功能,比如根据关键词快速搜索菜单,然后进入(现在系统页面上千个).系统版本自动更新等.同时我们也是规范使用,nanui的about窗口没有进行任何修改

**Comment by mrtylerzhou** [comment]
大佬有没有联系方式,或者有qq群什么的,强烈建议弄一个开发讨论群.

**Comment by XuanchenLin** [comment]
@mrtylerzhou 群一直都有，群号521854872，欢迎交流

**Comment by jrt324** [comment]
目前最新版本使用的chrome内核是什么版本？
