### ISSUE TITLE
github里增加版本号和版本描述

### ISSUE THREAD

**Issue by mrtylerzhou** [NetDimension/NanUI#96]
**你的想法 / Your idea...**
刚看了一下，github项目仓库release页是0.5，nuget包版本已经是0.7了，希望作者在有较大版本更新时增加github release页更新信息，便于了解项目的最新特性。像我已经在项目中使用nanui了，没有特殊原因也不会去下载新版本，但是我会关注使用到的软件的最新开发动态，如果在github release页里有更新信息真是太方便了。

**Comment by XuanchenLin** [comment]
从0.6之后release都会直接放到nuget，已把github的release页面删除。
