### ISSUE TITLE
[问题]可以给一个简单的开发案例教程吗？

### ISSUE THREAD

**Issue by fjmdc** [NetDimension/NanUI#97]
初次接触，请问可以给一个开发案例吗？比如内嵌好的设计界面、与winform窗体的交互等，谢谢？

**Comment by XuanchenLin** [comment]
文档和教学视频正在编写和制作中，很快会和大家见面，请稍后。

**Comment by XuanchenLin** [comment]
文档已作为知乎专栏更新
[NanUI 技术内幕](https://zhuanlan.zhihu.com/nanui)
