### ISSUE TITLE
如何重写WndProc方法?

### ISSUE THREAD

**Issue by zhangliang2008** [NetDimension/NanUI#98]
WndProc方法是protected,ContainerForm.WndProc不可访问.

**Comment by XuanchenLin** [comment]
这个方法我没有写在文档里，是为了将来跨平台兼容。既然有需求，那我还是介绍一下。
- 首先Formium子类中，WindowType设置为UserCustom
- 重载CreateCustomContainer方法，返回你自己的Form实例，你可以在子自己的Form里继承WndProc

**Comment by zhangliang2008** [comment]
感谢已经解决了,但是现在有个问题,我要自定义Form也想要无边框模式,但是现在无法拖动, 看了源码OnWebBrowserMessage你做了判断非无边框不返回Windows 消息,不改源码的情况下有办法实现拖动窗体吗?
