### ISSUE TITLE
[问题]新版本的中页面加载监听事件不需要注册了嘛？

### ISSUE THREAD

**Issue by 775709948** [NetDimension/NanUI#99]
LoadHandler_OnLoadEnd
LoadHandler_OnLoadStart 
现在不需要注册了嘛？
始终无法进入这两个事件

**Comment by zhangliang2008** [comment]
`protected override void OnWindowReady(IWebBrowserHandler browserClient)
        {

            browserClient.LoadHandler.OnLoadStart += LoadHandler_OnLoadStart;
            browserClient.LoadHandler.OnLoadEnd += LoadHandler_OnLoadEnd;
        }`

**Comment by 775709948** [comment]
非常感谢  谢谢

**Comment by 775709948** [comment]
非常感谢您的回复，谢谢

**Comment by 775709948** [comment]
success
